name: Build Windows EXE
on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.0, v1.2.3, etc.

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        pip install pygame mutagen pyinstaller
        
    - name: Build EXE
      run: |
        pyinstaller --onefile --distpath ./ --name Mixtaper.exe mixtaper.py
        
    - name: Commit EXE to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git stash
        git checkout main  # Ensure we're on main branch
        git stash apply
        git add Mixtaper.exe
        git commit -m "Build EXE for ${{ github.ref_name }}"
        git push origin HEAD:main
